[package]
name = "pub-sub-client"
version = "0.7.0"
edition = "2021"
rust-version = "1.58"

description = "Client library for Google Cloud Pub/Sub"
authors = [ "Heiko Seeberger <mail@heikoseeberger.rocks>" ]
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/hseeberger/pub-sub-client"
repository = "https://github.com/hseeberger/pub-sub-client"
documentation = "https://github.com/hseeberger/pub-sub-client"

[dependencies]
base64 = "0.*"
goauth = "0.*"
reqwest = { version = "0.*", features = [ "json" ] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
smpl_jwt = "0.*"
thiserror = "1.0"
time = { version = "0.*", features = [ "serde-well-known" ] }
tracing = "0.*"
tracing-subscriber = { version = "0.*", features = [ "env-filter", "fmt", "json", "tracing-log" ] }

[dev-dependencies]
anyhow = "1.0"
# TODO switch to the standard release once Pub/Sub has been included; until then use "dev"
testcontainers = { git = "https://github.com/testcontainers/testcontainers-rs", branch = "dev" }
tokio = { version = "1", features = [ "full" ] }
