name: CI

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.head_ref || github.run_id}}
  cancel-in-progress: true

jobs:
  toolchain:
    name: Setup Rust toolchain
    runs-on: ubuntu-latest
    outputs:
      toolchain: ${{steps.set_toolchain.outputs.toolchain}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Output toolchain
        id: set_toolchain
        env:
          toolchain_toml: "rust-toolchain.toml"
        run: |
          toolchain=$(grep channel rust-toolchain.toml | sed -r 's/channel = "(.*)"/\1/')
          echo "toolchain=$toolchain" | tee -a "$GITHUB_OUTPUT"

  fmt-check:
    name: Check Code Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
        with:
          toolchain: nightly-2025-12-08
          components: rustfmt

      - name: Install just
        uses: taiki-e/install-action@b8be7f5e140177087325943c4a8e169d01c59b3d # v2.75.3
        with:
          tool: just

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: just fmt-check
        run: |
          just fmt-check

  lint:
    runs-on: ubuntu-latest
    name: Lint Code
    needs: toolchain
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
        with:
          toolchain: ${{needs.toolchain.outputs.toolchain}}
          components: clippy

      - name: Install just
        uses: taiki-e/install-action@b8be7f5e140177087325943c4a8e169d01c59b3d # v2.75.3
        with:
          tool: just

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: just lint
        run: |
          rustup override set ${{needs.toolchain.outputs.toolchain}}
          just lint

  test:
    runs-on: ubuntu-latest
    name: Run Tests
    needs: toolchain
    env:
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
        with:
          toolchain: ${{needs.toolchain.outputs.toolchain}}

      - name: Install just
        uses: taiki-e/install-action@b8be7f5e140177087325943c4a8e169d01c59b3d # v2.75.3
        with:
          tool: just

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: just test
        run: |
          dir="$(mktemp -d)"
          echo "$GCP_SERVICE_ACCOUNT" > "$dir/service-account.json"
          export SERVICE_ACCOUNT_PATH="$dir/service-account.json"
          rustup override set ${{needs.toolchain.outputs.toolchain}}
          just test

  doc:
    runs-on: ubuntu-latest
    name: Create Documentation
    needs: toolchain
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
        with:
          toolchain: ${{needs.toolchain.outputs.toolchain}}
          components: rust-docs

      - name: Install just
        uses: taiki-e/install-action@b8be7f5e140177087325943c4a8e169d01c59b3d # v2.75.3
        with:
          tool: just

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: just doc
        run: |
          just doc
