name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: rustup update
      - run: cargo clippy -- -D warnings
      - name: Run `cargo test`
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        run: |
          printenv GCP_SERVICE_ACCOUNT > secrets/active-road-365118-2eca6b7b8fd9.json
          cargo test
